export const EXIT_DURATION_MS = 200;
export const TITLE_SCROLL_DURATION_MS = 180;
export const MENU_CLOSE_DURATION_MS = 280;
export const ARCHIVED_REVEAL_THRESHOLD = 80;
export const TOOLTIP_DELAY_MS = 500;
export const TAB_SWITCHER_VISIBLE_ITEM_COUNT = 10;
export const TAB_SWITCHER_ITEM_HEIGHT_PX = 28;
export const TAB_SWITCHER_MENU_CHROME_HEIGHT_PX = 18;
