export interface WelcomeQuote {
  readonly text: string;
  readonly author: string;
}

/** 欢迎页背景轮播的作者引文。 */
export const WELCOME_QUOTES: readonly WelcomeQuote[] = [
  { text: 'I could no more write a romance than an epic poem. I must keep to my own style and go on in my own way.', author: 'Jane Austen' },
  { text: 'The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.', author: 'Jane Austen' },
  { text: 'A fondness for reading, which, properly directed, must be an education in itself.', author: 'Jane Austen' },
  { text: 'You write in order to change the world, if you are able to change it, then at least to change the way people look at certain things.', author: 'James Baldwin' },
  { text: 'The purpose of art is to lay bare the questions which have been hidden by the answers.', author: 'James Baldwin' },
  { text: 'If you are going to be a writer there is nothing I can say to stop you; if you\'re not going to be a writer nothing I can say will help you.', author: 'James Baldwin' },
  { text: 'I have always imagined that Paradise will be a kind of library.', author: 'Jorge Luis Borges' },
  { text: 'I cannot sleep unless I am surrounded by books.', author: 'Jorge Luis Borges' },
  { text: 'I am not sure that I exist, actually. I am all the writers that I have read, all the people that I have met, all the women that I have loved, all the cities I have visited.', author: 'Jorge Luis Borges' },
  { text: 'He\'s more myself than I am. Whatever our souls are made of, his and mine are the same.', author: 'Emily Brontë' },
  { text: 'I wish I were a girl again, half savage and hardy, and free... and laughing at injuries, not maddening under them.', author: 'Emily Brontë' },
  { text: 'My love for Heathcliff resembles the eternal rocks beneath — a source of little visible delight, but necessary.', author: 'Emily Brontë' },
  { text: 'A classic is a book that has never finished saying what it has to say.', author: 'Italo Calvino' },
  { text: 'When I\'m writing a book, I prefer not to speak about it, because only when the book is finished can I try to understand what I\'ve really done.', author: 'Italo Calvino' },
  { text: 'The only kind of literature that is possible today: a literature that is both critical and creative.', author: 'Italo Calvino' },
  { text: 'Pain and suffering are always inevitable for a large intelligence and a deep heart.', author: 'Fyodor Dostoevsky' },
  { text: 'What is hell? I maintain that it is the suffering of being unable to love.', author: 'Fyodor Dostoevsky' },
  { text: 'Man is sometimes extraordinarily, passionately, in love with suffering...', author: 'Fyodor Dostoevsky' },
  { text: 'April is the cruellest month, breeding lilacs out of the dead land, mixing memory and desire.', author: 'T.S. Eliot' },
  { text: 'We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.', author: 'T.S. Eliot' },
  { text: 'For last year\'s words belong to last year\'s language. And next year\'s words await another voice.', author: 'T.S. Eliot' },
  { text: 'Sing in me, Muse, and through me tell the story of that man skilled in all ways of contending.', author: 'Homer' },
  { text: 'There is nothing more admirable than when two people who see eye to eye keep house as man and wife, confounding their enemies and delighting their friends.', author: 'Homer' },
  { text: 'Even his griefs are a joy long after to one that remembers all that he wrought and endured.', author: 'Homer' },
  { text: 'Writing is utter solitude, the descent into the cold abyss of oneself.', author: 'Franz Kafka' },
  { text: 'I think we ought to read only the kind of books that wound and stab us.', author: 'Franz Kafka' },
  { text: 'A book must be the axe for the frozen sea within us.', author: 'Franz Kafka' },
  { text: 'My imagination makes me human and makes me a fool; it gives me all the world and exiles me from it.', author: 'Ursula K. Le Guin' },
  { text: 'The unread story is not a story; it is little black marks on wood pulp. The reader, reading it, makes it alive.', author: 'Ursula K. Le Guin' },
  { text: 'If you haven\'t learned how to do something, the people who have may seem to be magicians.', author: 'Ursula K. Le Guin' },
  { text: 'If there\'s a book that you want to read, but it hasn\'t been written yet, then you must write it.', author: 'Toni Morrison' },
  { text: 'We die. That may be the meaning of life. But we do language. That may be the measure of our lives.', author: 'Toni Morrison' },
  { text: 'Oppressive language does more than represent violence; it is violence; does more than represent the limits of knowledge; it limits knowledge.', author: 'Toni Morrison' },
  { text: 'There\'s no such thing as perfect writing, just like there\'s no such thing as perfect despair.', author: 'Haruki Murakami' },
  { text: 'When I write fiction I go to weird, secret places in myself. It\'s like exploring the cosmos, but inside yourself.', author: 'Haruki Murakami' },
  { text: 'If you concentrate on writing three or four hours a day and feel tired after a week, you\'re not going to be able to write a long work. What\'s needed is endurance.', author: 'Haruki Murakami' },
  { text: 'Love is so short, forgetting is so long.', author: 'Pablo Neruda' },
  { text: 'I love you as certain dark things are to be loved, in secret, between the shadow and the soul.', author: 'Pablo Neruda' },
  { text: 'Poetry is an act of peace. Peace goes into the making of a poet as flour goes into the making of bread.', author: 'Pablo Neruda' },
  { text: 'Some say thronging cavalry, some say foot soldiers, others call a fleet the most beautiful of sights the dark earth offers, but I say it\'s whatever you love best.', author: 'Sappho' },
  { text: 'I could not hope to touch the sky with my two arms.', author: 'Sappho' },
  { text: 'You may forget but let me tell you this: someone in the future will remember us.', author: 'Sappho' },
  { text: 'All happy families are alike; each unhappy family is unhappy in its own way.', author: 'Leo Tolstoy' },
  { text: 'Everyone thinks of changing the world, but no one thinks of changing himself.', author: 'Leo Tolstoy' },
  { text: 'Love is life. All, everything that I understand, I understand only because I love.', author: 'Leo Tolstoy' },
  { text: 'A woman must have money and a room of her own if she is to write fiction.', author: 'Virginia Woolf' },
  { text: 'So long as you write what you wish to write, that is all that matters; and whether it matters for ages or only for hours, nobody can say.', author: 'Virginia Woolf' },
  { text: 'When I cannot see words curling like rings of smoke round me I am in darkness — I am nothing.', author: 'Virginia Woolf' },
  { text: 'A creative man is motivated by the desire to achieve, not by the desire to beat others.', author: 'Ayn Rand' },
  { text: 'If you don\'t know, the thing to do is not to get scared, but to learn.', author: 'Ayn Rand' },
  { text: 'The hardest thing to explain is the glaringly evident which everybody has decided not to see.', author: 'Ayn Rand' },
  { text: 'In its essence, any art that relies on words makes use of their ability to eat away — of their corrosive function — just as etching depends on the corrosive power of nitric acid.', author: 'Mishima Yukio' },
  { text: 'I want to make a poem of my life.', author: 'Mishima Yukio' },
  { text: 'What transforms this world is — knowledge. Do you see what I mean? Nothing else can change anything in this world.', author: 'Mishima Yukio' },
  { text: 'I write because I want to read books like the ones I write.', author: 'Ferit Orhan Pamuk' },
  { text: 'I write because I believe in literature, in the art of the novel, more than I believe in anything else.', author: 'Ferit Orhan Pamuk' },
  { text: 'I write not to tell a story, but to compose a story.', author: 'Ferit Orhan Pamuk' },
];
