import type { I18n, TranslationKey } from '../i18n';

// Keep this inventory synchronized when settings or section headings are added or renamed.
const SETTINGS_SEARCH_KEYS = [
  'settings.tabs.general',
  'settings.tabs.models',
  'settings.tabs.skills',
  'settings.tabs.tools',
  'settings.tabs.subagents',
  'settings.tabs.commands',
  'settings.language.name',
  'settings.layout',
  'settings.chatViewPlacement.name',
  'settings.tabBarPosition.name',
  'settings.chatBehavior',
  'settings.enableAutoScroll.name',
  'settings.deferMathRenderingDuringStreaming.name',
  'settings.autoTitle.name',
  'settings.compaction.title',
  'settings.compaction.autoCompact.name',
  'settings.compaction.threshold.name',
  'settings.compaction.keepRecent.name',
  'settings.personalizationContext',
  'settings.userName.name',
  'settings.excludedTags.name',
  'settings.inputShortcuts',
  'settings.requireCommandOrControlEnterToSend.name',
  'settings.navMappings.name',
  'settings.environment',
  'settings.sharedEnvironment.name',
  'settings.sessionFiles.heading',
  'settings.sessionFiles.deleteRemoved.name',
  'settings.integrations.heading',
  'settings.modelsTab.addProvider',
  'settings.modelsTab.candidateModels',
  'settings.modelsTab.endpointHeading',
  'settings.modelsTab.displayName',
  'settings.modelsTab.baseUrl',
  'settings.modelsTab.apiKey',
  'settings.modelsTab.oauthToken',
  'settings.modelsTab.authHeading',
  'settings.modelsTab.testProvider',
  'settings.skills.defaultBundle.name',
  'settings.skills.remote.heading',
  'settings.skills.remote.name',
  'settings.skills.installed.heading',
  'settings.tools.sections.builtIn',
  'settings.tools.sections.web',
  'settings.tools.sections.mcp',
  'settings.externalRead.heading',
  'settings.externalRead.allow.name',
  'settings.externalRead.directories.name',
  'settings.bash.heading',
  'settings.bash.allowlist.name',
  'settings.tools.heading',
  'settings.subagents.enableSpawn.name',
  'settings.subagents.allowBackground.name',
  'settings.subagents.maxConcurrent.name',
  'settings.slashCommandsUi.internalHeading',
  'settings.slashCommandsUi.heading',
  'settings.createCommand.name.name',
  'settings.createCommand.description.name',
  'settings.createCommand.argumentHint.name',
  'settings.createCommand.icon.name',
  'settings.createCommand.template.name',
  'settings.mcp.modal.serverName',
  'settings.mcp.modal.type',
  'settings.mcp.modal.command',
  'settings.mcp.modal.url',
  'settings.mcp.modal.env',
  'settings.mcp.modal.headersName',
  'settings.mcp.modal.authHeading',
] as const satisfies readonly TranslationKey[];

export function getSettingsSearchAliases(i18n: I18n): string[] {
  return [...new Set(SETTINGS_SEARCH_KEYS
    .map((key) => i18n.t(key))
    .filter((label) => label.length > 0 && !label.includes('{')))];
}
