import type { I18n } from '../i18n';
import { SETTINGS_PAGES, type SettingsPageId } from './navigation';

export type { SettingsPageId } from './navigation';
export { SETTINGS_PAGES } from './navigation';

/** Former flat search-key inventory; each key is owned by exactly one page in `SETTINGS_PAGES`. */
export const FORMER_SETTINGS_SEARCH_KEYS = [
  'settings.tabs.general',
  'settings.tabs.models',
  'settings.tabs.skills',
  'settings.tabs.tools',
  'settings.tabs.subagents',
  'settings.tabs.commands',
  'settings.tabs.toolbar',
  'settings.tabs.prompt',
  'settings.tabs.about',
  'settings.about.heading',
  'settings.about.github',
  'settings.about.issues',
  'settings.language.name',
  'settings.layout',
  'settings.chatViewPlacement.name',
  'settings.tabBarPosition.name',
  'settings.chatBehavior',
  'settings.enableAutoScroll.name',
  'settings.showCacheHitRate.name',
  'settings.showTokensPerSecond.name',
  'settings.deferMathRenderingDuringStreaming.name',
  'settings.autoTitle.name',
  'settings.providerRequests.title',
  'settings.providerRequests.total.name',
  'settings.providerRequests.idle.name',
  'settings.personalizationContext',
  'settings.userName.name',
  'settings.excludedTags.name',
  'settings.inputShortcuts',
  'settings.requireCommandOrControlEnterToSend.name',
  'settings.environment',
  'settings.sharedEnvironment.name',
  'settings.sessionFiles.heading',
  'settings.sessionFiles.retention.name',
  'settings.sessionFiles.deleteRemoved.name',
  'settings.styleSettings.name',
  'settings.editorToolbar.provider.title',
  'settings.editorToolbar.provider.name',
  'settings.editorToolbar.title',
  'settings.editorToolbar.addEditorCommand',
  'settings.editorToolbar.addPiviCommand',
  'settings.noteToolbar.heading',
  'settings.modelsTab.addProvider',
  'settings.modelsTab.candidateModels',
  'settings.modelsTab.contextWindowOverridePlaceholder',
  'settings.modelsTab.reasoningOverrideDesc',
  'settings.modelsTab.thinkingFormatOverrideDesc',
  'settings.modelsTab.endpointHeading',
  'settings.modelsTab.displayName',
  'settings.modelsTab.baseUrl',
  'settings.modelsTab.modelIds',
  'settings.modelsTab.apiKey',
  'settings.modelsTab.oauthToken',
  'settings.modelsTab.authHeading',
  'settings.modelsTab.testProvider',
  'settings.skills.defaultBundle.name',
  'settings.skills.remote.heading',
  'settings.skills.remote.name',
  'settings.skills.installed.heading',
  'settings.tools.sections.builtIn',
  'settings.tools.sections.web',
  'settings.tools.sections.mcp',
  'settings.externalRead.heading',
  'settings.externalRead.allow.name',
  'settings.externalRead.directories.name',
  'settings.bash.heading',
  'settings.bash.allowlist.name',
  'settings.tools.reading.defaultSize.name',
  'settings.tools.heading',
  'settings.subagents.enableSpawn.name',
  'settings.subagents.allowBackground.name',
  'settings.subagents.maxConcurrent.name',
  'settings.slashCommandsUi.internalHeading',
  'settings.slashCommandsUi.heading',
  'settings.createCommand.name.name',
  'settings.createCommand.description.name',
  'settings.createCommand.argumentHint.name',
  'settings.createCommand.icon.name',
  'settings.createCommand.template.name',
  'settings.prompt.workflow.heading',
  'settings.prompt.custom.heading',
  'settings.prompt.usage.heading',
  'settings.mcp.modal.serverName',
  'settings.mcp.modal.type',
  'settings.mcp.modal.url',
  'settings.mcp.modal.headersName',
  'settings.mcp.modal.authHeading',
] as const;

/** Retired tab keys: they mapped to page labels, not row aliases. */
export const RETIRED_SETTINGS_TAB_SEARCH_KEYS = [
  'settings.tabs.general',
  'settings.tabs.models',
  'settings.tabs.skills',
  'settings.tabs.tools',
  'settings.tabs.subagents',
  'settings.tabs.commands',
  'settings.tabs.toolbar',
  'settings.tabs.prompt',
  'settings.tabs.about',
] as const;

export function getSettingsPageSearchAliases(i18n: I18n, page: SettingsPageId): string[] {
  const descriptor = SETTINGS_PAGES[page];
  const pageLabel = i18n.t(descriptor.labelKey);
  return [...new Set(descriptor.aliasKeys
    .map((key) => i18n.t(key))
    .filter((label) => label.length > 0 && !label.includes('{') && label !== pageLabel))];
}
